### ISSUE TITLE
Error message and suggestions

### ISSUE THREAD

**Issue by lppezzi** [castelao/maud#14]
This message appears in the terminal while running...
pezzi-pc:filtro lppezzi$ maud4latlonnc --largerpasslength=600e3 --var='tt' -w hamming --npes=12 --o no_mesoscale.nc sst_wrp.nc
 Will work with 12 npes
Preparing the workers.
Collecting the results.
Error: Couldn't find per display information

**Comment by castelao** [comment]
@lppezzi , I'm so sorry! I think I never saw this. I hope you have found another alternative. Cheers!
